import { Command } from 'commander';
import { describe, expect, it } from 'vitest';
import { examples } from '../src/commands/examples.js';
import { applyGlobalOptions, registerCommands } from '../src/commands/register.js';
import type { Runner } from '../src/commands/types.js';

/**
 * Examples are attached to the command definitions, so they reach both
 * `--help` and the generated docs/commands.md. These assert the formatting the
 * docs generator depends on, and that no command ships without examples — the
 * failure mode being a new command whose flags are listed but never shown
 * combined.
 */

/** The real command tree, built with a no-op runner (as `completion` does). */
async function commandTree(): Promise<Command> {
  const program = new Command('kite');
  applyGlobalOptions(program);
  const noop: Runner = () => async () => {};
  await registerCommands(program, noop);
  return program;
}

/**
 * The help a user actually sees. `helpInformation()` renders the usage block
 * alone — text added with `addHelpText` is only emitted by `outputHelp()`,
 * which is what both the terminal and the docs generator go through.
 */
function helpText(cmd: Command): string {
  let captured = '';
  cmd.configureOutput({
    writeOut: (str) => {
      captured += str;
    },
  });
  cmd.outputHelp();
  return captured;
}

/** Every command and subcommand, minus commander's synthetic `help`. */
function walk(cmd: Command, path: string[] = []): Array<{ name: string; command: Command }> {
  const found: Array<{ name: string; command: Command }> = [];
  for (const child of cmd.commands) {
    if (child.name() === 'help') continue;
    const name = [...path, child.name()].join(' ');
    found.push({ name, command: child });
    found.push(...walk(child, [...path, child.name()]));
  }
  return found;
}

describe('examples()', () => {
  it('aligns descriptions and opens with a blank line', () => {
    const block = examples([
      ['kite quote NSE:INFY', 'One instrument'],
      ['kite quote NSE:INFY NSE:TCS', 'Two instruments'],
    ]);

    expect(block).toBe(
      [
        '',
        'Examples:',
        '  $ kite quote NSE:INFY          One instrument',
        '  $ kite quote NSE:INFY NSE:TCS  Two instruments',
        '',
      ].join('\n'),
    );
  });

  it('drops a description onto its own line when the command is too wide', () => {
    const block = examples([
      ['kite ltp NSE:INFY', 'Short'],
      ['kite orders place NSE:INFY -s BUY -q 1000 --variety iceberg --iceberg-legs 5', 'Long'],
      ['kite orders place NSE:INFY -s SELL -q 10 -t SL -p 1595 --trigger-price 1600', 'Also long'],
    ]);

    // Wide commands are excluded from the alignment column entirely, so the one
    // short example is not pushed off an 80-column terminal.
    for (const line of block.split('\n')) expect(line.length).toBeLessThanOrEqual(100);
    expect(block).toContain('\n      Long');
    // With most commands too wide to align, the block wraps as a whole rather
    // than leaving one stray aligned line.
    expect(block).toContain('\n      Short');
  });
});

describe('every command', () => {
  it('carries an Examples block in its help', async () => {
    const program = await commandTree();
    const missing = walk(program)
      .filter(({ command }) => !helpText(command).includes('Examples:'))
      .map(({ name }) => name);

    expect(missing).toEqual([]);
  });

  it('keeps a blank line between Commands: and Examples: on group commands', async () => {
    const program = await commandTree();
    // docs/commands.md is generated by parsing `--help`, and its subcommand
    // capture ends at the first blank line after `Commands:`. Losing that line
    // would silently drop every subcommand from the reference page.
    const groups = walk(program).filter(({ command }) => command.commands.some((c) => c.name() !== 'help'));
    expect(groups.length).toBeGreaterThan(0);

    for (const { name, command } of groups) {
      const help = helpText(command);
      expect(help, name).toMatch(/\nCommands:\n[\s\S]*?\n\nExamples:\n/);
    }
  });
});
